version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data/
  web:
    build: .
    command: >
        bash -c "chmod +x wait-for-it.sh &&
        ./wait-for-it.sh db:5432 -- 
        python /code/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
